// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartEnergyExpert.Client.Data;

#nullable disable

namespace SmartEnergyExpert.Client.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.AcousticSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmplitudeDb")
                        .HasColumnType("numeric");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DepthMeters")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FrequencyBand")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NoiseLevelDb")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RangeMeters")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SoundSpeed")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId", "Timestamp", "FrequencyBand");

                    b.ToTable("AcousticSamples");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.ComparisonRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FieldDatasetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Mae")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MeanRelativeErrorPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("P95AbsoluteError")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rmse")
                        .HasColumnType("numeric");

                    b.Property<int>("SignificantDifferenceCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SimulationDatasetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalComparedPoints")
                        .HasColumnType("integer");

                    b.Property<string>("VisualizationPayloadJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FieldDatasetId");

                    b.HasIndex("SimulationDatasetId");

                    b.ToTable("ComparisonRuns");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.Dataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TimeRangeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TimeRangeStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Type", "SourceSystem");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.DifferencePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AbsoluteError")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ComparisonRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FieldValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FrequencyBand")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RelativeErrorPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SimulationValue")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonRunId", "Severity", "Timestamp", "FrequencyBand");

                    b.ToTable("DifferencePoints");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ComparisonRunId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric");

                    b.Property<string>("ConfidenceRationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceSignalsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InferenceMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuggestedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonRunId", "Confidence");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.AcousticSample", b =>
                {
                    b.HasOne("SmartEnergyExpert.Client.Entities.Dataset", "Dataset")
                        .WithMany("Samples")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.AuditLog", b =>
                {
                    b.HasOne("SmartEnergyExpert.Client.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.ComparisonRun", b =>
                {
                    b.HasOne("SmartEnergyExpert.Client.Entities.Dataset", "FieldDataset")
                        .WithMany()
                        .HasForeignKey("FieldDatasetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartEnergyExpert.Client.Entities.Dataset", "SimulationDataset")
                        .WithMany()
                        .HasForeignKey("SimulationDatasetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FieldDataset");

                    b.Navigation("SimulationDataset");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.DifferencePoint", b =>
                {
                    b.HasOne("SmartEnergyExpert.Client.Entities.ComparisonRun", "ComparisonRun")
                        .WithMany("Differences")
                        .HasForeignKey("ComparisonRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComparisonRun");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.Recommendation", b =>
                {
                    b.HasOne("SmartEnergyExpert.Client.Entities.ComparisonRun", "ComparisonRun")
                        .WithMany("Recommendations")
                        .HasForeignKey("ComparisonRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComparisonRun");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.User", b =>
                {
                    b.HasOne("SmartEnergyExpert.Client.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.ComparisonRun", b =>
                {
                    b.Navigation("Differences");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.Dataset", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("SmartEnergyExpert.Client.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
